### ISSUE TITLE
Using Traefik with lastest PeerTube image

### ISSUE THREAD

**Issue by merklemonk** [kimsible/getpeer.tube#1]
Thank you for making this single file script. I find this to be a great solution for future maintenance and upgrades.

With the removal of traefik from PeerTube's docker-compose solution as of https://github.com/Chocobozzz/PeerTube/pull/2531#event-3985367055 does that create conflict with your `install.sh` getting the latest peertube docker image?

On install I ran into this issue with a fresh Ubuntu LTS with Docker VPS

```
Start PeerTube #
peertube_postgres_1 is up-to-date
Creating peertube_reverse-proxy_1 ... 
Creating peertube_redis_1         ... 

Creating peertube_redis_1         ... done
Creating peertube_postfix_1       ... done
Creating peertube_peertube_1      ... done
Creating peertube_webserver_1     ... done

ERROR: for reverse-proxy  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 201, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1177, in up
  File "compose/cli/main.py", line 1173, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 106, in parallel_execute
  File "compose/parallel.py", line 204, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 563, in execute_convergence_plan
  File "compose/service.py", line 479, in _execute_convergence_create
  File "compose/parallel.py", line 106, in parallel_execute
  File "compose/parallel.py", line 204, in producer
  File "compose/service.py", line 477, in <lambda>
  File "compose/service.py", line 456, in create_and_start
  File "compose/service.py", line 333, in create_container
  File "compose/service.py", line 937, in _get_container_create_options
  File "compose/service.py", line 1069, in _get_container_host_config
  File "docker/api/container.py", line 598, in create_host_config
  File "docker/types/containers.py", line 339, in __init__
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
[10398] Failed to execute script docker-compose
Attaching to peertube_peertube_1
```
all other parts of the compose worked perfectly.

**Comment by kimsible** [comment]
Thank @merklemonk for reminding me this. It's time to drop traefik =).

**Comment by kimsible** [comment]
It should be fixed with https://github.com/kimsible/install-peertube/commit/f629f269cce4748143b093fb1028fb04df31bf5a
